// apps/web/src/routes/register/+page.svelte
<script lang="ts">
	import { Button, Label } from 'bits-ui';
	import LoaderCircle from '@lucide/svelte/icons/loader-circle';
	import * as z from 'zod';
	import { toast } from 'svelte-sonner';
	import { authClient } from '$lib/client';
	import type { RegisterResponse, RegisterResult } from '$lib/gen/auth/auth_pb';

	let registerLoading = $state<boolean>(false);

	const Register = z.object({
		email: z.email(),
		password: z.string().min(6).max(24)
	});

	type RegisterData = z.infer<typeof Register>;
	let registerData = $state<RegisterData>({
		email: '',
		password: ''
	});

	function handleError() {
		const form = document.getElementById('register-form');
		const body = document.body;
		if (form) {
			form.classList.remove('animate-headshake');
			body.classList.remove('bg-red-50');
			void form.offsetWidth;
			form.classList.add('animate-headshake');
			body.classList.add('bg-red-50');

			form.addEventListener(
				'animationend',
				() => {
					setTimeout(() => {
						form.classList.remove('animate-headshake');
						body.classList.remove('bg-red-50');
					}, 1700);
				},
				{
					once: true
				}
			);
		}
	}

	function handleFail(result: z.ZodSafeParseResult<RegisterData>) {
		if (result.success) return true;
		console.log(result);

		const message = result.error.issues[0].message;
		toast.error(message, {
			duration: 2500
		});

		handleError();

		registerLoading = false;
		return false;
	}

	async function handleSubmit(e: Event) {
		e.preventDefault();
		registerLoading = true;

		const result = Register.safeParse(registerData);
		if (!handleFail(result)) return;

		try {
			const data: RegisterResult = await authClient.register({
				email: registerData.email,
				password: registerData.password
			});

			if (data.result.case === 'error') {
				toast.error(data.result.value.message);
				handleError();
			} else {
				toast.success('Account created!');
			}
		} catch (err: any) {
			toast.error(err?.message || 'Registration failed');
		} finally {
			registerLoading = false;
		}
	}
</script>

<div id="register-form" class="flex h-screen flex-col items-center justify-center gap-8">
	<h1 class="px-12 font-serif text-3xl">Create a Shulker account</h1>

	<form onsubmit={handleSubmit} class="flex w-full flex-col gap-6">
		<div class="flex w-full flex-col gap-2">
			<Label.Root for="email" class="w-full">Email</Label.Root>
			<input
				bind:value={registerData.email}
				disabled={registerLoading}
				id="email"
				type="email"
				placeholder="Email Address"
				class="round h-10 w-full border px-2.5 text-sm disabled:opacity-70"
			/>
		</div>
		<div class="flex w-full flex-col gap-2">
			<Label.Root for="password" class="w-full">Password</Label.Root>
			<input
				bind:value={registerData.password}
				disabled={registerLoading}
				id="password"
				type="password"
				placeholder="Password"
				class="round h-10 w-full border px-2.5 text-sm disabled:opacity-70"
			/>
		</div>
		<Button.Root
			type="submit"
			disabled={registerLoading}
			class="round flex h-10 flex-row items-center justify-center gap-2 bg-primary text-sm text-primary-foreground hover:bg-primary/90 disabled:opacity-70"
		>
			{#if registerLoading}
				<LoaderCircle class="size-4 animate-spin text-primary-foreground/60" />
			{/if}
			Register
		</Button.Root>
		<Button.Root
			disabled={registerLoading}
			href="/login"
			class="text-center text-muted-foreground hover:text-primary hover:no-underline disabled:opacity-70"
			>Already signed up? Login here</Button.Root
		>
	</form>
</div>

// web/src/pages/Register.tsx
import { Logo } from "@/components/core/Logo";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Spinner } from "@/components/ui/spinner";
import { motion } from "framer-motion";
import { API_URL } from "@/lib/utils";
import type { AuthResponse } from "@/responses/auth";
import { toast } from "sonner";

export default function Register() {
    const [registering, setRegistering] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const canContinue = useMemo(() => {
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        return (
            email.length > 0 && password.length >= 8 && emailRegex.test(email)
        );
    }, [email, password]);

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        setRegistering(true);

        try {
            const res = await fetch(`${API_URL}/auth/register`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: await JSON.stringify({
                    email: email,
                    display_name: email.split("@")[0],
                    password: password,
                }),
                credentials: "include",
            });

            const data = (await res.json()) as AuthResponse;
            toast.success("Successfully registered!");
            window.location.href = "/";
        } catch (error: unknown) {
            if (error instanceof Error) {
                setError(error.message);
                setTimeout(() => {
                    setError(null);
                }, 2500);
            }
        } finally {
            setRegistering(false);
        }
    };

    return (
        <div
            className={`h-screen bg-background w-screen flex-col gap-4 flex items-center justify-start pt-48 ${
                error ? "" : ""
            }`}
        >
            <form
                onSubmit={handleSubmit}
                className={`flex flex-col relative p-4 py-12 pb-16 border rounded-lg transition-all duration-200 items-center gap-4 w-[450px] px-4 ${
                    error
                        ? "head-shake bg-red-50 border border-red-100"
                        : "border-transparent"
                }`}
            >
                {error && (
                    <p className="absolute bottom-[-1rem] bg-red-100 text-red-400 px-4 text-sm font-medium p-2 rounded-lg">
                        {error}
                    </p>
                )}
                <Logo hasText={false} />
                <header className="flex flex-col items-center mb-6">
                    <h1 className="font-medium text-xl">
                        Register for an account
                    </h1>
                    <p className="text-muted-foreground mt-1">
                        Storage made simple, secure, and accessible.
                    </p>
                </header>
                <div className="grid w-full max-w-sm items-center gap-3">
                    <Label
                        className={
                            registering
                                ? "opacity-70 hover:cursor-not-allowed pointer-events-none"
                                : ""
                        }
                        htmlFor="email"
                    >
                        Email
                    </Label>
                    <Input
                        onChange={(e) => setEmail(e.target.value)}
                        disabled={registering}
                        type="email"
                        id="email"
                        placeholder="Email"
                    />
                </div>
                <div className="grid w-full max-w-sm items-center gap-3 mt-1">
                    <Label
                        className={
                            registering
                                ? "opacity-70 hover:cursor-not-allowed pointer-events-none"
                                : ""
                        }
                        htmlFor="password"
                    >
                        Password
                    </Label>
                    <Input
                        onChange={(e) => setPassword(e.target.value)}
                        disabled={registering}
                        type="password"
                        id="password"
                        placeholder="Password"
                    />
                </div>
                <Button
                    type="submit"
                    disabled={registering || !canContinue}
                    className="w-full max-w-sm mt-1 transition-all duration-300"
                >
                    {registering ? "Registering..." : "Register"}
                    <motion.div
                        initial={{
                            opacity: 0,
                            marginRight: 4,
                            scale: 0,
                        }}
                        animate={
                            registering
                                ? {
                                      opacity: 1,
                                      marginRight: 12,
                                      scale: 1,
                                  }
                                : {
                                      opacity: 0,
                                      marginRight: 4,
                                      scale: 0,
                                  }
                        }
                        transition={{ duration: 0.3, ease: [0.33, 1, 0.68, 1] }}
                    >
                        <Spinner
                            className={`${
                                registering ? "inline-block" : "hidden"
                            }`}
                        />
                    </motion.div>
                </Button>
                <Link to="/login" className="text-muted-foreground text-sm">
                    Already have an account? Log in
                </Link>
            </form>
        </div>
    );
}
